# Generated by Django 4.1.1 on 2022-10-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opinionsuser",
            name="created",
        ),
    ]
