# Generated by Django 4.1.1 on 2022-09-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Leido")),
                (
                    "fullname",
                    models.CharField(max_length=80, verbose_name="Nombre completo"),
                ),
                ("email", models.EmailField(max_length=120, verbose_name="Email")),
                ("message", models.CharField(max_length=50, verbose_name="Mensaje")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefono")),
                ("date_contact", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
