# Generated by Django 4.1.1 on 2022-10-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "verbose_name": "Consulta de contacto - Restaurante Sentidos",
                "verbose_name_plural": "Consultas de contacto - Restaurante Sentidos",
            },
        ),
    ]
