# Generated by Django 4.1.1 on 2022-10-21 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Categoria de Productos - Restaurante Sentidos y Casa de Te.",
                "verbose_name_plural": "Categorias de Productos - Restaurante Sentidos y Casa de Te.",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Nombre producto"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Sin descripcion...",
                        max_length=80,
                        null=True,
                        verbose_name="Descripcion",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Precio")),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Imagen representativa",
                    ),
                ),
                (
                    "published",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de publicacion"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto - Restaurante Sentidos",
                "verbose_name_plural": "Productos - Restaurante Sentidos",
                "ordering": ("-name",),
            },
        ),
    ]
