# Generated by Django 4.1.1 on 2022-10-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, to="product.category", verbose_name="Categoria"
            ),
        ),
    ]
