# Generated by Django 4.1.1 on 2022-11-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre del menu"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        to="product.product",
                        verbose_name="Productos del menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu - Restaurante Sentidos & Casa de Te",
            },
        ),
    ]
