# Generated by Django 4.1.1 on 2022-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Nombre"),
        ),
    ]
