# Generated by Django 4.1.1 on 2022-10-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=50, verbose_name="Telefono celular"),
                ),
                ("schedule", models.CharField(max_length=20, verbose_name="Horario")),
                (
                    "date",
                    models.CharField(
                        max_length=50, verbose_name="Fecha de Reservacion"
                    ),
                ),
                (
                    "selected_tables",
                    models.CharField(max_length=80, verbose_name="Mesas seleccionadas"),
                ),
                (
                    "paid_parcial",
                    models.BooleanField(default=False, verbose_name="Pagado Parcial"),
                ),
                (
                    "paid",
                    models.BooleanField(default=False, verbose_name="Pagado Total"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservacion",
                "verbose_name_plural": "Reservaciones - Restaurante Sentidos.",
            },
        ),
    ]
