# Generated by Django 4.1.1 on 2022-11-08 12:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_mesa",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Mesa",
                    ),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False, verbose_name="Esta seleccionado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=50, verbose_name="Telefono celular"),
                ),
                ("schedule", models.CharField(max_length=20, verbose_name="Horario")),
                ("date", models.DateField(verbose_name="Fecha")),
                ("paid", models.BooleanField(default=False, verbose_name="Pagado")),
                (
                    "selected_tables",
                    models.ManyToManyField(blank=True, to="reservation.tables"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservacion",
                "verbose_name_plural": "Reservaciones - Restaurante Sentidos.",
            },
        ),
    ]
