# Generated by Django 4.1.1 on 2022-11-01 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservation", "0001_initial"),
        ("product", "0002_remove_product_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Method_Pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedidos - Restaurante Sentidos y Casa de Te",
            },
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                ("price", models.FloatField(default=1, verbose_name="Precio")),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checking_in.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                through="checking_in.ProductOrder",
                to="product.product",
                verbose_name="Productos",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.tables",
                verbose_name="Mesa",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("number_invoice", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "method_pay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checking_in.method_pay",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checking_in.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facturas - Restaurante Sentidos y Casa de Te",
            },
        ),
    ]
