# Generated by Django 4.1.1 on 2022-11-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking_in", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pay",
            field=models.BooleanField(default=False, verbose_name="Pagado"),
        ),
    ]
