# Generated by Django 4.1.1 on 2022-11-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking_in", "0002_order_pay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="method_pay",
            options={
                "verbose_name": "Metodos de pagos - Restaurante Sentidos y Casa de Te"
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="totalPrice",
            field=models.FloatField(default=1, verbose_name="Precio total"),
            preserve_default=False,
        ),
    ]
