# Generated by Django 4.1.1 on 2022-10-31 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checking_in", "0003_method_pay_invoice_method_pay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
    ]
